redo-web/config/routes.rb
Rails.application.routes.draw do
  resources :faces
  resources :rotations
  resources :redos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

redo-web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

redo-web/app/models/face.rb
class Face < ApplicationRecord
end

redo-web/app/models/redo.rb
class Redo < ApplicationRecord
end

redo-web/app/models/rotation.rb
class Rotation < ApplicationRecord
end

redo-web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

redo-web/app/controllers/faces_controller.rb
class FacesController < ApplicationController
  before_action :set_face, only: [:show, :edit, :update, :destroy]

  # GET /faces
  # GET /faces.json
  def index
    @faces = Face.all
  end

  # GET /faces/1
  # GET /faces/1.json
  def show
  end

  # GET /faces/new
  def new
    @face = Face.new
  end

  # GET /faces/1/edit
  def edit
  end

  # POST /faces
  # POST /faces.json
  def create
    @face = Face.new(face_params)

    respond_to do |format|
      if @face.save
        format.html { redirect_to @face, notice: 'Face was successfully created.' }
        format.json { render :show, status: :created, location: @face }
      else
        format.html { render :new }
        format.json { render json: @face.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faces/1
  # PATCH/PUT /faces/1.json
  def update
    respond_to do |format|
      if @face.update(face_params)
        format.html { redirect_to @face, notice: 'Face was successfully updated.' }
        format.json { render :show, status: :ok, location: @face }
      else
        format.html { render :edit }
        format.json { render json: @face.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faces/1
  # DELETE /faces/1.json
  def destroy
    @face.destroy
    respond_to do |format|
      format.html { redirect_to faces_url, notice: 'Face was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_face
      @face = Face.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def face_params
      params.require(:face).permit(:redo_id, :face_id, :text, :status)
    end
end

redo-web/app/controllers/redos_controller.rb
class RedosController < ApplicationController
  before_action :set_redo, only: [:show, :edit, :update, :destroy]

  # GET /redos
  # GET /redos.json
  def index
    @redos = Redo.all
  end

  # GET /redos/1
  # GET /redos/1.json
  def show
  end

  # GET /redos/new
  def new
    @redo = Redo.new
  end

  # GET /redos/1/edit
  def edit
  end

  # POST /redos
  # POST /redos.json
  def create
    @redo = Redo.new(redo_params)

    respond_to do |format|
      if @redo.save
        format.html { redirect_to @redo, notice: 'Redo was successfully created.' }
        format.json { render :show, status: :created, location: @redo }
      else
        format.html { render :new }
        format.json { render json: @redo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /redos/1
  # PATCH/PUT /redos/1.json
  def update
    respond_to do |format|
      if @redo.update(redo_params)
        format.html { redirect_to @redo, notice: 'Redo was successfully updated.' }
        format.json { render :show, status: :ok, location: @redo }
      else
        format.html { render :edit }
        format.json { render json: @redo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /redos/1
  # DELETE /redos/1.json
  def destroy
    @redo.destroy
    respond_to do |format|
      format.html { redirect_to redos_url, notice: 'Redo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_redo
      @redo = Redo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def redo_params
      params.require(:redo).permit(:type, :version, :key)
    end
end

redo-web/app/controllers/report_controller.rb
class ReportController < ApplicationController
    def create
        logger.info("Create called with #{params}")
    end
end

redo-web/app/controllers/rotations_controller.rb
class RotationsController < ApplicationController
  before_action :set_rotation, only: [:show, :edit, :update, :destroy]

  # GET /rotations
  # GET /rotations.json
  def index
    @rotations = Rotation.all
  end

  # GET /rotations/1
  # GET /rotations/1.json
  def show
  end

  # GET /rotations/new
  def new
    @rotation = Rotation.new
  end

  # GET /rotations/1/edit
  def edit
  end

  # POST /rotations
  # POST /rotations.json
  def create
    @rotation = Rotation.new(rotation_params)

    respond_to do |format|
      if @rotation.save
        format.html { redirect_to @rotation, notice: 'Rotation was successfully created.' }
        format.json { render :show, status: :created, location: @rotation }
      else
        format.html { render :new }
        format.json { render json: @rotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rotations/1
  # PATCH/PUT /rotations/1.json
  def update
    respond_to do |format|
      if @rotation.update(rotation_params)
        format.html { redirect_to @rotation, notice: 'Rotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @rotation }
      else
        format.html { render :edit }
        format.json { render json: @rotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rotations/1
  # DELETE /rotations/1.json
  def destroy
    @rotation.destroy
    respond_to do |format|
      format.html { redirect_to rotations_url, notice: 'Rotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rotation
      @rotation = Rotation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rotation_params
      params.require(:rotation).permit(:face, :redo_id)
    end
end

redo-web/app/helpers/application_helper.rb
module ApplicationHelper
end

redo-web/app/helpers/faces_helper.rb
module FacesHelper
end

redo-web/app/helpers/redos_helper.rb
module RedosHelper
end

redo-web/app/helpers/report_helper.rb
module ReportHelper
end

redo-web/app/helpers/rotations_helper.rb
module RotationsHelper
end

redo-web/app/views/faces/_form.html.erb
<%= form_with(model: face) do |form| %>
  <% if face.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(face.errors.count, "error") %> prohibited this face from being saved:</h2>

      <ul>
        <% face.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :redo_id %>
    <%= form.text_field :redo_id %>
  </div>

  <div class="field">
    <%= form.label :face_id %>
    <%= form.text_field :face_id %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

redo-web/app/views/faces/edit.html.erb
<h1>Editing Face</h1>

<%= render 'form', face: @face %>

<%= link_to 'Show', @face %> |
<%= link_to 'Back', faces_path %>

redo-web/app/views/faces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faces</h1>

<table>
  <thead>
    <tr>
      <th>Redo</th>
      <th>Face</th>
      <th>Text</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faces.each do |face| %>
      <tr>
        <td><%= face.redo_id %></td>
        <td><%= face.face_id %></td>
        <td><%= face.text %></td>
        <td><%= face.status %></td>
        <td><%= link_to 'Show', face %></td>
        <td><%= link_to 'Edit', edit_face_path(face) %></td>
        <td><%= link_to 'Destroy', face, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Face', new_face_path %>

redo-web/app/views/faces/new.html.erb
<h1>New Face</h1>

<%= render 'form', face: @face %>

<%= link_to 'Back', faces_path %>

redo-web/app/views/faces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Redo:</strong>
  <%= @face.redo_id %>
</p>

<p>
  <strong>Face:</strong>
  <%= @face.face_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @face.text %>
</p>

<p>
  <strong>Status:</strong>
  <%= @face.status %>
</p>

<%= link_to 'Edit', edit_face_path(@face) %> |
<%= link_to 'Back', faces_path %>

redo-web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedoWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

redo-web/app/views/redos/_form.html.erb
<%= form_with(model: redo) do |form| %>
  <% if redo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(redo.errors.count, "error") %> prohibited this redo from being saved:</h2>

      <ul>
        <% redo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :version %>
    <%= form.text_field :version %>
  </div>

  <div class="field">
    <%= form.label :key %>
    <%= form.text_area :key %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

redo-web/app/views/redos/edit.html.erb
<h1>Editing Redo</h1>

<%= render 'form', redo: @redo %>

<%= link_to 'Show', @redo %> |
<%= link_to 'Back', redos_path %>

redo-web/app/views/redos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Redos</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Version</th>
      <th>Key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @redos.each do |redo| %>
      <tr>
        <td><%= redo.type %></td>
        <td><%= redo.version %></td>
        <td><%= redo.key %></td>
        <td><%= link_to 'Show', redo %></td>
        <td><%= link_to 'Edit', edit_redo_path(redo) %></td>
        <td><%= link_to 'Destroy', redo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Redo', new_redo_path %>

redo-web/app/views/redos/new.html.erb
<h1>New Redo</h1>

<%= render 'form', redo: @redo %>

<%= link_to 'Back', redos_path %>

redo-web/app/views/redos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @redo.type %>
</p>

<p>
  <strong>Version:</strong>
  <%= @redo.version %>
</p>

<p>
  <strong>Key:</strong>
  <%= @redo.key %>
</p>

<%= link_to 'Edit', edit_redo_path(@redo) %> |
<%= link_to 'Back', redos_path %>

redo-web/app/views/rotations/_form.html.erb
<%= form_with(model: rotation) do |form| %>
  <% if rotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rotation.errors.count, "error") %> prohibited this rotation from being saved:</h2>

      <ul>
        <% rotation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :face %>
    <%= form.text_field :face %>
  </div>

  <div class="field">
    <%= form.label :redo_id %>
    <%= form.text_field :redo_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

redo-web/app/views/rotations/edit.html.erb
<h1>Editing Rotation</h1>

<%= render 'form', rotation: @rotation %>

<%= link_to 'Show', @rotation %> |
<%= link_to 'Back', rotations_path %>

redo-web/app/views/rotations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rotations</h1>

<table>
  <thead>
    <tr>
      <th>Face</th>
      <th>Redo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rotations.each do |rotation| %>
      <tr>
        <td><%= rotation.face %></td>
        <td><%= rotation.redo_id %></td>
        <td><%= link_to 'Show', rotation %></td>
        <td><%= link_to 'Edit', edit_rotation_path(rotation) %></td>
        <td><%= link_to 'Destroy', rotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rotation', new_rotation_path %>

redo-web/app/views/rotations/new.html.erb
<h1>New Rotation</h1>

<%= render 'form', rotation: @rotation %>

<%= link_to 'Back', rotations_path %>

redo-web/app/views/rotations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Face:</strong>
  <%= @rotation.face %>
</p>

<p>
  <strong>Redo:</strong>
  <%= @rotation.redo_id %>
</p>

<%= link_to 'Edit', edit_rotation_path(@rotation) %> |
<%= link_to 'Back', rotations_path %>